name: CI

on:
  push:
    branches: ["main", "continuous-deployment"]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: ["main"]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '19.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build project for production
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run tests
        run: npm test
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Configure SSH
        run: |
          echo "$SSH_KEY" > github_actions_key && chmod 600 github_actions_key
          ssh -o StrictHostKeyChecking=no -i github_actions_key ${SSH_USER}@${SSH_HOST} 'ls -l'
        env:
          SSH_HOST: ${{ vars.AWS_HOST }}
          SSH_USER: ${{ vars.AWS_USER }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          
